Restructure `dispatch` macro related exports
paritytech/polkadot-sdk pull request #1162
Opened 2023-08-25 13:17 UTC by juangirini

Partial for https://github.com/paritytech/polkadot-sdk/issues/172

2023-08-26 14:28 UTC, sam0x17 approved these changes

2023-08-26 16:00 UTC, bkchr approved these changes

2023-08-26 17:38 UTC, liamaharon requested changes
LGTM, just need to remove the .gitignore

2023-08-26 17:38 UTC, liamaharon commented on .gitignore
> +.DS_Store
👀

2023-08-26 17:38 UTC, liamaharon commented on substrate/frame/support/src/dispatch_context.rs
> +//! [`UnfilteredDispatchable`](frame_support::traits::UnfilteredDispatchable) for each pallet `Call`
cool, I had no idea you could link with []() 🤯

2023-08-26 17:40 UTC, liamaharon approved these changes
Disregard prev. review, I see now it was a merge conflict

2023-08-26 18:04 UTC, ggwpez approved these changes

2023-08-26 18:04 UTC, ggwpez commented on polkadot/runtime/common/src/claims.rs
> -	use frame_support::dispatch::UnfilteredDispatchable;
Now we just need 1 MR instead of three, what a breeze :relieved:

2023-08-26 18:04 UTC, ggwpez commented
bot fmt

2023-08-28 09:26 UTC, juangirini commented
bot rebase

2023-08-29 15:17 UTC, sam0x17 approved these changes

2023-08-30 07:11 UTC, acatangiu approved these changes

2023-08-31 09:09 UTC, ordian approved these changes

2023-08-31 11:08 UTC, merged