Fix polkadot-node-core-pvf-prepare-worker build with jemalloc
paritytech/polkadot-sdk pull request #1315
Opened 2023-08-30 15:58 UTC by Morganamilo

The jemalloc feature on polkadot-node-core-pvf-prepare-worker depended on some feature gated code in polkadot-node-core-pvf-common but there way no way to enable this feature gate.

This commit adds the feature and makes prepare-worker enable it.

2023-08-30 20:23 UTC, bkchr approved these changes

2023-08-31 09:01 UTC, mrcnski requested changes
Thank you! Looks like it was lost when we split up the pvf crates. Few more issues:

1. The `tikv-jemalloc-ctl` dependency can be removed from `execute-worker/Cargo.toml` (note that it's listed twice).
2. The `jemalloc-allocator` feature can be added to `pvf/Cargo.toml`, it should list `"polkadot-node-core-pvf-common/jemalloc-allocator"`.
3. The `jemalloc-allocator` feature in `polkadot/Cargo.toml` should list `polkadot-node-core-pvf`.
4. The `tikv-jemallocator` dep in `polkadot/Cargo.toml` can be made optional, and added to the Linux-specific list of deps (same as was done in `execute-worker/Cargo.toml`).
5. Maybe there should be a CI job that runs `cargo check` on non-Linux with this feature enabled?

Phew, that's a lot. I can take care of it, I'll just need help with (5). Thanks again!!

2023-08-31 09:12 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3509284

2023-08-31 11:08 UTC, Morganamilo commented
Thanks for being more in the know about this and fixing the other issues.

2023-08-31 13:04 UTC, ordian approved these changes

2023-08-31 15:13 UTC, mrcnski approved these changes

2023-08-31 15:13 UTC, merged