Retire puppet workers
paritytech/polkadot-sdk pull request #1449
Opened 2023-09-07 14:25 UTC by s0me0ne-unkn0wn

Closes #583

2023-09-08 10:10 UTC, mrcnski requested changes
Really happy to see this!

This requires the workers to be built before running tests, right? Instructions should be added to the relevant READMEs, like we do for `polkadot-test-service`.

2023-09-10 10:15 UTC, s0me0ne-unkn0wn commented
@mrcnski I've added a README to the PVF host integration tests directory. Not sure if it has to be added somewhere else, all the other tests seem good to go, but I may be missing something.

2023-09-10 10:57 UTC, mrcnski approved these changes

2023-09-11 09:07 UTC, alindima approved these changes

2023-09-11 09:31 UTC, bkchr approved these changes

2023-09-11 17:14 UTC, merged