Merge CODEOWNERS
paritytech/polkadot-sdk pull request #1472
Opened 2023-09-08 14:59 UTC by chevdor

This PR merged the previous `CODEOWNERS` files.

See also #1415

2023-09-09 20:24 UTC, bkchr approved these changes

2023-09-09 20:28 UTC, bkchr commented
@franciscoaguirre I added polkadot-sdk to the xcm team.

2023-09-09 21:54 UTC, franciscoaguirre commented
@bkchr I added the rule to the file, but it's still giving an error.
I think it's because we have only "read" access, we need "write" according to GitHub.

![image](https://github.com/paritytech/polkadot-sdk/assets/4390772/ef9da235-b67d-461e-b438-ec201df2d581)

2023-09-09 22:03 UTC, bkchr commented
> @bkchr I added the rule to the file, but it's still giving an error.
> I think it's because we have only "read" access, we need "write" according to GitHub.
> 
> ![image](https://github.com/paritytech/polkadot-sdk/assets/4390772/ef9da235-b67d-461e-b438-ec201df2d581)
> 

Fixed.

2023-09-10 08:47 UTC, kianenigma approved these changes

2023-09-11 08:37 UTC, alvicsam requested changes

2023-09-11 08:37 UTC, alvicsam commented on .github/CODEOWNERS
> +/scripts/ci/ @paritytech/ci @paritytech/release-engineering
```suggestion
/.gitlab/ @paritytech/ci
```
Currently there is no `scripts` folder and I'm not sure that we should return it back.

2023-09-11 09:24 UTC, alvicsam approved these changes

2023-09-11 09:33 UTC, merged