Implement wrapping of EPM types
paritytech/polkadot-sdk pull request #1600
Opened 2023-09-17 06:04 UTC by wirednkod

This PR wraps the `Snapshot`, `SnapshotMetadata` and `DesiredTargets` storage items in the [EPM pallet](https://paritytech.github.io/substrate/master/pallet_election_provider_multi_phase/index.html) in order to keep them in sync throughout the election lifetime and in order to be killed together. 

Prior to this PR, these storage items were mutated in different places in the pallet;

In addition 2 helper `fns` are introduced for chekcing if all the wrapped storage items exist or not;

Fixes #413 ;

2023-09-17 06:12 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721279

2023-09-17 06:12 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721280

2023-09-17 06:12 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721281

2023-09-17 07:11 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721436

2023-09-17 07:11 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721437

2023-09-17 07:11 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721435

2023-09-17 09:11 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721843

2023-09-17 09:11 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721844

2023-09-17 09:11 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3721842

2023-09-18 11:16 UTC, lexnv commented on substrate/frame/election-provider-multi-phase/src/lib.rs
> +pub struct SnapshotWrapper<T>(PhantomData<T>);
nit: Could add a small documentation that this wrapper handles the synchronization of `Snapshot`, `SnapshotMetadata` and `DesiredTargets`

2023-09-18 11:19 UTC, lexnv approved these changes
LGTM! Disclaimer: i'm not super familiar with the code base

2023-09-19 08:01 UTC, sergejparity approved these changes

2023-09-19 08:56 UTC, kianenigma requested changes
diff is broken. Blocking to make sure it is not merged before someone from @paritytech/staking-core approves.

2023-09-19 10:07 UTC, wirednkod commented
Thank you @kianenigma . I messed up the repo configuration from merge to rebase. I will open a new PR fixing the mess. Apologies

2023-09-19 11:29 UTC, wirednkod commented
Closing this in favour of #1633

2023-09-19 11:29 UTC, closed without merging