Use `Extensions` to register offchain worker custom extensions
paritytech/polkadot-sdk pull request #1719
Opened 2023-09-26 17:51 UTC by skunert

Closes #1671 

As discovered correctly in that issue, custom externality extensions passed in from the outside as `Box<dyn Extension>` have some limitations. We store them in `Extensions` were the key is a `TypeId`, so multiple extensions are overriding each other.

I think the solution proposed in the issue is reasonable, so I changed the return type of the `custom_extensions` closure to return `Extensions`. They can then be passed to the runtime instance and merged with the existing extensions.

2023-09-26 17:52 UTC, skunert commented on substrate/primitives/api/proc-macro/src/impl_runtime_apis.rs
> +				fn register_extensions(&mut self, extension: #crate_::Extensions) {
The alternative would be to offer some `register_with_type_id` here.

2023-09-26 19:47 UTC, davxy commented
Just an idea, but what about adding a method to the `Extension` trait to return an identifier [here](https://github.com/skunert/polkadot-sdk/blob/bce7c2465cfa11cdf51f0160fafecc7ef02e5a75/substrate/primitives/externalities/src/extensions.rs#L38). (i.e. a method like `get_id() -> ExtId` with `ExtId` something  like `const [u8; N]`).

And then use that id to populate the map

https://github.com/skunert/polkadot-sdk/blob/bce7c2465cfa11cdf51f0160fafecc7ef02e5a75/substrate/primitives/externalities/src/extensions.rs#L161-L162

For sure using the `TypeId` is more easy to use and less prone to collision (if not in this case where using the `Box<dyn Extension>`. But if the trait implementors are careful enough creating their unique ids maybe this could be a viable solution

2023-09-26 21:37 UTC, bkchr requested changes
We should probably remove the `Any` supertrait from `Extension`. Then we can forward the `type_id` function of `Box<dyn Extension` to the wrapped type. This would ensure that we don't take the `TypeId` of `Box<Extension>`. This should then probably fix this issue without requiring any of the changes in this pr.

2023-09-27 21:27 UTC, bkchr approved these changes

2023-09-27 21:27 UTC, bkchr commented on substrate/primitives/externalities/src/extensions.rs
> +	/// Get the [`std::any::TypeId`] of this `Extension`.
```suggestion
	/// Get the [`TypeId`] of this `Extension`.
```

2023-09-28 06:50 UTC, michalkucharczyk approved these changes

2023-09-28 07:25 UTC, davxy approved these changes

2023-09-29 07:37 UTC, merged