Implements maximum validator payout per era
paritytech/polkadot-sdk pull request #1859
Opened 2023-10-12 09:13 UTC by gpestana

Related to and possibly replacing https://github.com/paritytech/polkadot-sdk/pull/1660

2023-10-12 09:16 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3946274

2023-11-06 09:16 UTC, kianenigma commented on polkadot/runtime/test-runtime/src/lib.rs
> +	type MaxValidatorsPayout = MaxValidatorsPayout;
```suggestion
```

If you were to do this approach, I don't think there is any need to pass `MaxValidatorsPayout` to the staking pallet. Whatever cap is needed, should already be applied to `RewardCurve` or whatever type is implementing `type EraPayout`.

2023-11-06 09:17 UTC, kianenigma requested changes
A bit wrong because of https://github.com/paritytech/polkadot-sdk/pull/1859/files#r1382983349, but in any case we probably won't need it.

2023-11-06 11:42 UTC, gpestana commented
Closing due to https://github.com/paritytech/polkadot-sdk/issues/403#issuecomment-1794635026

2023-11-06 11:42 UTC, closed without merging