add link to rfc-0001 in broker README
paritytech/polkadot-sdk pull request #1862
Opened 2023-10-12 12:44 UTC by takahser

# Description
- What does this PR do?
  - link added
- Why are these changes needed?
  - improve docs
- How were these changes implemented and what do they affect?
  - only concerns docs

2023-10-12 16:29 UTC, ggwpez approved these changes
We should also invest in a proper pallet documentation, currently there is none 🙈

2023-10-12 19:35 UTC, takahser commented
@ggwpez here you go.

2023-10-12 19:46 UTC, joepetrowski commented on substrate/frame/broker/README.md
> +You're absolutely right, I missed covering some of the events in the `Event` enum in the Rust code. Let me add the missing events:
?

2023-10-12 21:12 UTC, ggwpez requested changes
Uhm with "pallet documentation" i meant this: https://github.com/paritytech/polkadot-sdk/blob/master/docs/DOCUMENTATION_GUIDELINES.md#pallet-crates  
README files are obsolete unter this schema. So either rollback or go all the way please.

2023-10-13 04:27 UTC, takahser commented on substrate/frame/broker/README.md
> +You're absolutely right, I missed covering some of the events in the `Event` enum in the Rust code. Let me add the missing events:
```suggestion
```

2023-10-13 04:40 UTC, takahser commented
@ggwpez ok thx, updated the following:

- rolled back changes
- fixed another broken link

2023-10-13 05:04 UTC, takahser commented on substrate/frame/broker/README.md
> +You're absolutely right, I missed covering some of the events in the `Event` enum in the Rust code. Let me add the missing events:
Thanks, LLM leftovers 😄.

2023-10-13 06:48 UTC, ggwpez approved these changes

2023-10-15 07:30 UTC, joepetrowski approved these changes

2023-10-15 07:59 UTC, bkchr approved these changes

2023-10-15 08:00 UTC, merged