Allow `sudo::set_key` to remove the Key
paritytech/polkadot-sdk pull request #2165
Opened 2023-11-05 19:12 UTC by ggwpez

Changes:
- Use `Option<AccountIdLookupOf<T>>` as `new` for `set_key` to allow removing the sudo key. This is a less-invasive way of rendering the sudo pallet useless without needing a code upgrade.
- Remove some clones and general maintenance

2023-11-05 19:17 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4218686

2023-11-06 03:38 UTC, liamaharon approved these changes

2023-11-06 10:11 UTC, jasl commented
What about adding a `remove_key` to remove `root`?
By default, `polkadot.js` sets `None` for optional fields. I guess a tiny probability set the `sudo key` to `None` accidentally and unexpectedly, and the result is critical.
A `remove_key` is more explicit.

2023-11-06 10:52 UTC, ggwpez commented
> What about adding a `remove_key` to remove `root`? By default, `polkadot.js` sets `None` for optional fields. I guess a tiny probability set the `sudo key` to `None` accidentally and unexpectedly, and the result is critical. A `remove_key` is more explicit.

Yea I also thought about this. But am not sure if we should write our Rust code in such a fashion only to appease a single downstream UI with insane default values...

2023-11-06 11:57 UTC, bkchr requested changes

2023-11-06 11:57 UTC, bkchr commented on substrate/frame/sudo/src/lib.rs
>  			}
```suggestion
			if Self::key().map_or(false, |k| k == sender) {
				Ok(())
			} else {
				Err(Error::<T>::RequireSudo.into())
			}
```

2023-11-06 11:57 UTC, bkchr commented on substrate/frame/sudo/src/lib.rs
> +			new: Option<AccountIdLookupOf<T>>,
Yeah, I would go with what @jasl said and introduce a `remove_key` function

2023-11-06 14:03 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4228297

2023-11-06 14:18 UTC, bkchr approved these changes
Nice!

2023-11-07 16:14 UTC, lexnv approved these changes

2023-11-07 17:09 UTC, ggwpez commented
bot bench -v PIPELINE_SCRIPTS_REF=oty-fix-runtimes substrate-pallet --pallet=pallet_sudo  
bot bench -v PIPELINE_SCRIPTS_REF=oty-fix-runtimes polkadot-pallet --pallet=pallet_sudo --runtime=westend  
bot bench -v PIPELINE_SCRIPTS_REF=oty-fix-runtimes polkadot-pallet --pallet=pallet_sudo --runtime=rococo

2023-11-08 11:59 UTC, merged