Move un-opinionated runtime macros from `frame-support` to `sp-runtime`
paritytech/polkadot-sdk pull request #2443
Opened 2023-11-22 11:46 UTC by muraca

As per title, this solves some of the problems introduced in #211 
- macros `ensure`, `fail` and `runtime_print` have been moved to a new module `macros` in `sp-runtime`; `frame-support` re-exports them.
- the no-bound macros have been moved to a new crate `sp-runtime-procedural`; they are re-exported by `sp-runtime`.

2023-11-22 11:52 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4433521

2023-11-22 11:53 UTC, ggwpez commented on bridges/bin/runtime-common/src/messages_xcm_extension.rs
> +use sp_runtime::{CloneNoBound, EqNoBound, PartialEqNoBound, SaturatedConversion};
Why do you have to change it if they are re-exported?

2023-11-22 11:54 UTC, ggwpez commented on substrate/frame/atomic-swap/src/lib.rs
> -	RuntimeDebugNoBound,
?

2023-11-22 11:56 UTC, ggwpez commented on substrate/frame/support/procedural/src/lib.rs
> +/// 	frame_support::sp_runtime::PartialEqNoBound,
`sp_runtime` should not be exported at top-level.

2023-11-22 12:21 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4434174

2023-11-23 16:58 UTC, ggwpez reviewed
I dont understand this Merge request. Is it supposed to be a breaking change or not?  
The description reads as if everything is still re-exported, although i see that many files need to have their imports changed.

2023-11-23 16:59 UTC, ggwpez commented on substrate/frame/contracts/src/migration/v11.rs
> -use frame_support::{pallet_prelude::*, storage_alias, DefaultNoBound};
Why was this removed? It does clearly not build anymore. Please check the CI output.

2023-11-23 17:01 UTC, muraca commented
This is not supposed to be a breaking change and you're 100% right. I'll make `frame-support` re-export the `no-bound` macros and revert the superfluous changes.

2023-11-24 13:10 UTC, ggwpez commented on substrate/frame/support/src/traits/tokens/fungibles/imbalance.rs
> -use sp_runtime::traits::Zero;
>This is not supposed to be a breaking change

Then why do the imports change here 🤔 ?

2023-11-24 19:33 UTC, ggwpez requested changes
There are still changed imports, as i mentioned above.

2023-11-25 07:18 UTC, bkchr commented on substrate/frame/support/procedural/src/lib.rs
> -pub fn derive_clone_no_bound(input: TokenStream) -> TokenStream {
If we are moving these, we should move them into a complete separate crate that is living outside of the repo etc. IMO this makes this reusable by more people.

2024-03-25 07:53 UTC, closed without merging