fix overflow in `balance_to_point` conversion
paritytech/polkadot-sdk pull request #2706
Opened 2023-12-14 05:40 UTC by SCJangra

Closes #416

As I mentioned in the above issue `balance_to_points` conversion currently overflows the `Balance` types even before computing the actual points for the given tokens. This fixes that,

2023-12-18 20:32 UTC, gpestana requested changes
Thanks for the PR, it looks like a fix for this issue. One improvement could be adding some tests that ensure that the conversion is working as expected and the bounds are safe and that would fail with the code before the PR, wdyt?

As a suggestion, something along these lines:

```rust
        #[test]
	fn points_and_balance_conversions_are_safe() {
		ExtBuilder::default().build_and_execute(|| {
			let bonded_pool = BondedPool::<Runtime> {
				id: 123123,
				inner: BondedPoolInner {
					commission: Commission::default(),
					member_counter: 1,
					points: u128::MAX,
					roles: DEFAULT_ROLES,
					state: PoolState::Open,
				},
			};
			StakingMock::set_bonded_balance(bonded_pool.bonded_account(), u128::MAX);

			// max out the points and balance of the pool and make sure the conversion works as
			// expected ans does not overflow.
			assert_eq!(bonded_pool.balance_to_point(u128::MAX), u128::MAX);
			assert_eq!(bonded_pool.points_to_balance(u128::MAX), u128::MAX);
		})
	}
```

2023-12-19 10:55 UTC, SCJangra commented
@gpestana I've shamelessly copied the code you posted into tests, I can't think of any more tests specifically for this issue. Let me know if you need anything else changed/added.

2023-12-19 12:36 UTC, ggwpez approved these changes

2023-12-19 16:27 UTC, gpestana approved these changes
Great, thanks!

2023-12-22 12:21 UTC, bkchr approved these changes

2023-12-22 12:23 UTC, merged