Allow skipping block history download in warp sync
paritytech/polkadot-sdk pull request #2710
Opened 2023-12-14 10:37 UTC by tmpolaczyk

Adds a new sync mode `--warp-no-block-history` that is exactly the same as `--warp`, but doesn't download block history.

Close #8

2023-12-14 10:42 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4724646

2023-12-18 09:55 UTC, tomaka commented
I don't know whether it is already the case as I'm not familiar with the sync code, but we must make sure that, no matter what, the block headers and justifications of session change blocks are downloaded anyway.

Otherwise it won't be possible for other nodes to warp sync from your node, which means that if enough people run with this option we could completely break warp syncing altogether.

2023-12-18 11:32 UTC, dmitry-markin commented
> but we must make sure that, no matter what, the block headers and justifications of session change blocks are downloaded anyway.

As far as I can read the code, that's not the case — as a result of warp sync we only import target block body, state, and justifications. So it won't be possible to warp sync from a node that skipped block history phase.

Also, it needs to be carefully evaluated if adding nodes not able to provide syncing from genesis is safe for network. And likely address https://github.com/paritytech/polkadot-sdk/issues/523 first.

So, right now adding an option to turn off gap sync (block history phase) sounds risky.

2023-12-18 11:40 UTC, tmpolaczyk commented
Thanks for your comments. Is the justifications problem something that affects only the relaychain, or does it affects parachains as well? Because I only need this feature for syncing parachains, so I could modify the pr to error if trying to sync a relaychain.

Otherwise is there any way to make this a hidden sync mode or something? Because for my use case it doesn't matter if other nodes are not able to sync from this one.

2023-12-18 11:40 UTC, tomaka commented
> Also, it needs to be carefully evaluated if adding nodes not able to provide syncing from genesis is safe for network. And likely address https://github.com/paritytech/polkadot-sdk/issues/523 first.

I've recently noticed that more and more nodes refuse to serve warp sync requests. Currently, around 20% of warp sync requests fail on Westend, and after a small investigation it seems that it's because they target nodes that have blocks pruning enable.

While it's not alarming yet, it could become alarming if people enable the mode that this PR adds.

2023-12-18 11:42 UTC, tomaka commented
> Because for my use case it doesn't matter if other nodes are not able to sync from this one.

The problem that we're talking about is a tragedy of the commons type of problem.
If you alone enable this mode then there's no problem, but the more people enable it the worse the syncing will become for everyone.

2023-12-18 11:45 UTC, girazoki commented
can we make it under a feature flag? Our usecase is rotating-collators that connect to a full-node that has the history of a chain. The collators are not intended to store the history.

Now using full-sync but then enabling block-prunning has the same implications as this PR right?

2023-12-18 11:49 UTC, tomaka commented
An alternative way is that nodes that have this mode enabled do not participate in the DHT at all.

Light clients currently do not participate in the DHT at all because they would otherwise be polluting the network similar to how nodes that have this mode enabled would be polluting the network.

> Now using full-sync but then enabling block-prunning has the same implications as this PR right?

Yes, but that doesn't make it correct. See https://github.com/paritytech/polkadot-sdk/issues/2733.

2023-12-18 14:10 UTC, bkchr requested changes
This will first require: https://github.com/paritytech/polkadot-sdk/issues/2738 and https://github.com/paritytech/polkadot-sdk/issues/2733 

I would also not add a new warp sync mode and instead this should be decided based on the blocks-pruning/state pruning flags.

2023-12-18 14:15 UTC, tmpolaczyk commented
@bkchr regarding block prunning, I was thinking the same. I just tested that running `--sync warp --blocks-pruning=100` does still download the full block history. So in that case we want to only download `HEADER | BODY | JUSTIFICATION` of the latest 100 blocks, and `HEADER | JUSTIFICATION` of the full block history. Is that correct?

2023-12-18 14:27 UTC, bkchr commented
> So in that case we want to only download `HEADER | BODY | JUSTIFICATION` of the latest 100 blocks

Not sure I would care that much about this part, but it would be for sure the cleanest implementation. We will need some kind of implementation that handles the "dynamic nature", as the node will continue to import and finalize new blocks. This means, the "ultimate" last block to download moves all the time. However, it should not be that complicated to implement and also downloading one more block is probably fine.

> and `HEADER | JUSTIFICATION` of the full block history.

The beauty of https://github.com/paritytech/polkadot-sdk/issues/2738 would be that we do not need to download them, as we already downloaded them as part of the warp proof. When we have support for syncing from a checkpoint, we will not have all the justifications back from the genesis anymore. We could then discuss to download them or we would expect that all nodes always use some recent checkpoint.

2023-12-18 15:05 UTC, dmitry-markin commented
To give a heads up — as the syncing is currently being heavily refactored in preparation for Sync 2.0, it's better to wait at least for https://github.com/paritytech/polkadot-sdk/pull/2467 and follow-up warp sync strategy PRs to be merged before implementing improvements to warp sync. Otherwise we'll end up with a lot of conflicts.

2023-12-18 15:57 UTC, tmpolaczyk commented
Ok, I will close this PR given that it needs to be rewritten anyway. If after sync 2.0 this functionality is still missing I will open a new PR. Thank you all for your input!

2023-12-18 15:57 UTC, closed without merging