Added Event for nominator
paritytech/polkadot-sdk pull request #3279
Opened 2024-02-09 09:14 UTC by arunjot12

I've added a new event for the function `nominate`[L1193](https://github.com/paritytech/polkadot-sdk/blob/b2c81b5800ffd5528dac26c2fc4059d43ed7404b/substrate/frame/staking/src/pallet/mod.rs#L1193)

2024-02-09 09:35 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5168144

2024-02-12 11:05 UTC, gpestana requested changes
As I mentioned, I'm not necessarily opposed to this new event but I don't agree with the naming. Also, could you improve the tests to make sure that the event is deposited when `nominate` is called?

2024-02-12 11:05 UTC, gpestana commented on substrate/frame/staking/src/pallet/mod.rs
> +		NominatorPrefsSet { who: T::AccountId, prefs: Nominations<T> },
I'm not necessarily opposed to this new event, however I'd rename it to `Nominated {who, nominations}` to be more clear and inline with the semantics we use in staking.

2024-02-13 08:58 UTC, arunjot12 commented
I've changed the name and added a test case for the nominator. Please check

2024-02-23 04:03 UTC, arunjot12 commented
Hi @gpestana. Please review the changes

2024-03-08 12:48 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5473204

2024-03-15 07:30 UTC, arunjot12 commented
Hi @gpestana. Can you please check now

2024-04-10 11:37 UTC, arunjot12 commented
Hi. @gpestana . Can you please review

2026-09-14 05:59 UTC, Captain1653 commented
Hi.

I am reviewing old pull requests and found this one.

* **Inactivity Period**: This pull request has experienced over 2 years of inactivity since it was opened in February 2024.

* **Context Loss**: While the technical mechanism of the added event is clear, the broader integration context remains missing — it is unclear which specific service, indexer, or consumer actually requires this event to function.

Considering the long period of inactivity and the fact that it remains unclear who actually needed this solution, I propose closing this pull request.

2026-09-14 07:36 UTC, sigurpol commented
> Hi.
> 
> I am reviewing old pull requests and found this one.
> 
> * **Inactivity Period**: This pull request has experienced over 2 years of inactivity since it was opened in February 2024.
> * **Context Loss**: While the technical mechanism of the added event is clear, the broader integration context remains missing — it is unclear which specific service, indexer, or consumer actually requires this event to function.
> 
> Considering the long period of inactivity and the fact that it remains unclear who actually needed this solution, I propose closing this pull request.

it's also targeting the old legacy staking pallet. Closing

2026-09-14 07:36 UTC, closed without merging