Permissioned contract deployment
paritytech/polkadot-sdk pull request #3377
Opened 2024-02-18 16:28 UTC by Szegoo

Closes: #3196

2024-02-18 16:30 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5247525

2024-02-18 16:30 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5247543

2024-02-18 16:30 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5247542

2024-02-18 16:35 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5247849

2024-02-18 16:40 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5247960

2024-02-18 17:38 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5248114

2024-02-26 04:23 UTC, athei requested changes
This PR does not check the `InstantiateOrigin` when a contract instantiates another contract. Is this intended? No matter what the answer this has to be documented on the `Config` knob.

2024-02-26 06:47 UTC, Szegoo commented
> This PR does not check the `InstantiateOrigin` when a contract instantiates another contract. Is this intended? 

Yes, this was intended, as I think it should probably be up to the contract logic to regulate other contract instantiation.

2024-03-01 01:44 UTC, athei commented on substrate/frame/contracts/src/lib.rs
> +		/// Origin allowed to upload code.
We need some explanation here that it is a safe default to allow everyone to upload code and permissioned code deployment is a special case.

2024-03-01 01:44 UTC, athei commented on substrate/frame/contracts/src/lib.rs
> +		/// NOTE: This is not enforced when a contract instantiates another contract.
```suggestion
		/// Origin allowed to instantiate code.
		///
		/// # Note
		///
		/// This is not enforced when a contract instantiates another contract. The [`UploadOrigin`] should
		/// make sure that no code is deployed that does unwanted instantiations.
```

2024-03-01 01:53 UTC, athei reviewed
Tests are insufficient. The instantiation extrinsics are not tested. You also need to define a special implementation for `EnsureOrigin` where you can change what it does dynamically. Have a look how we do that with `parameter_types!` for our `TestExtension`.  This will allow you to change what it does for your tests while leave it as-is for the existing tests.

2024-03-01 09:41 UTC, Szegoo commented
> The instantiation extrinsics are not tested. 

It was actually tested, the instantiation origin was configured to allow any signed origin to deploy, and there was already a `root_cannot_instantiate` test. 

Based on your suggestion, I added more tests by dynamically restricting upload and instantiation, so it is better tested now.

2024-03-01 09:42 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5406537

2024-03-02 05:28 UTC, athei approved these changes

2024-03-02 05:28 UTC, athei commented on substrate/frame/contracts/src/lib.rs
> +		/// This is not enforced when a contract instantiates another contract. The [`UploadOrigin`]
```suggestion
		/// This is not enforced when a contract instantiates another contract. The [`Self::UploadOrigin`]
```

2024-03-02 05:28 UTC, athei commented on substrate/frame/contracts/src/tests.rs
> +	static InstantiateOrigin: <Test as frame_system::Config>::AccountId = ALICE;
```suggestion
	static UploadAccount: <Test as frame_system::Config>::AccountId = ALICE;
	static InstantiateAccount: <Test as frame_system::Config>::AccountId = ALICE;
```

2024-03-04 09:08 UTC, pgherveou commented
@Szegoo seeing your PR a bit late commented here
https://github.com/paritytech/polkadot-sdk/issues/3196#issuecomment-1976047906

Haven't look at the code here yet, but from the description it seems that this is something that can be done already. Can you double check and tell me what you think

2024-03-04 15:28 UTC, Szegoo commented
This is more configurable. `dispatch_as` requires the origin to be root, while here the upload and instantiate origin could be set to anything(e.g. a collective).

2024-03-04 17:26 UTC, pgherveou approved these changes

2024-03-04 17:26 UTC, pgherveou commented on substrate/frame/contracts/src/tests.rs
> +
Maybe we can just  use a single type here for both Upload & Instantiate Origin

```suggestion
parameter_types! {
	pub static UploadAccount: Option<<Test as frame_system::Config>::AccountId> = None;
	pub static InstantiateAccount: Option<<Test as frame_system::Config>::AccountId> = None;
}

pub struct EnsureAccount<T, A>(sp_std::marker::PhantomData<(T, A)>);
impl<T: Config, A: sp_core::Get<Option<crate::AccountIdOf<T>>>>
	EnsureOrigin<<T as frame_system::Config>::RuntimeOrigin> for EnsureAccount<T, A>
where
	<T as frame_system::Config>::AccountId: From<AccountId32>,
{
	type Success = T::AccountId;

	fn try_origin(o: T::RuntimeOrigin) -> Result<Self::Success, T::RuntimeOrigin> {
		let who = <frame_system::EnsureSigned<_> as EnsureOrigin<_>>::try_origin(o.clone())?;
		if matches!(A::get(), Some(a) if who != a) {
			return Err(o)
		}

		Ok(who)
	}

	#[cfg(feature = "runtime-benchmarks")]
	fn try_successful_origin() -> Result<T::RuntimeOrigin, ()> {
		Err(())
	}
}
```

Then fix up 
```diff
-	type UploadOrigin = EnsureUploadAccount<Self>;
-	type InstantiateOrigin = EnsureInstantiateAccount<Self>;
+	type UploadOrigin = EnsureAccount<Self, UploadAccount>;
+	type InstantiateOrigin = EnsureAccount<Self, InstantiateAccount>;
 	type MaxDebugBufferLen = ConstU32<{ 2 * 1024 * 1024 }>;
 	type RuntimeHoldReason = RuntimeHoldReason;
 	type Migrations = crate::migration::codegen::BenchMigrations;
@@ -6007,7 +5980,7 @@ fn root_cannot_instantiate() {
 #[test]
 fn only_upload_origin_can_upload() {
 	let (wasm, _) = compile_module::<Test>("dummy").unwrap();
-	RestrictedUpload::set(true);
+	UploadAccount::set(Some(ALICE));
```

2024-03-04 18:49 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5431858

2024-03-05 06:08 UTC, athei requested changes
> `dispatch_as` requires the origin to be root, while here the upload and instantiate origin could be set to anything(e.g. a collective).

Are you sure this is true? You should be able to check the origin in the filter. Zeitgeist is not doing this but you could do that, right?

2024-03-05 08:27 UTC, Szegoo commented
> Are you sure this is true?

I was referring to:
https://github.com/paritytech/polkadot-sdk/blob/ec30d2f5da839a7fb3f34778013c63e5afc9e90f/substrate/frame/utility/src/lib.rs#L390

Not so sure about checking the origin in the filter though.

2024-03-05 08:35 UTC, athei commented
Yes this is understood. Probably should have quoted this:

> This is more configurable.

Because you don't need to use `dispatch_as` as Zeitgeist does I think. You should be able to check the origin in the filter.

2024-03-05 08:40 UTC, pgherveou commented
> > `dispatch_as` requires the origin to be root, while here the upload and instantiate origin could be set to anything(e.g. a collective).
> 
> Are you sure this is true? You should be able to check the origin in the filter. Zeitgeist is not doing this but you could do that, right?

I don't think you can the filter only give you access to the RuntimeCall

2024-03-05 08:42 UTC, pgherveou commented
https://github.com/paritytech/polkadot-sdk/blob/c34ad77d0524add1ef7cec3de72df7874c67f8a9/substrate/frame/system/src/lib.rs?plain=1#L444-L455

2024-03-06 00:49 UTC, athei approved these changes
Yes you are right. The filter does not allow access to the origin.

2024-03-06 01:21 UTC, merged