Contracts: Fix delegate_dependency length in benchmark
paritytech/polkadot-sdk pull request #3558
Opened 2024-03-04 10:50 UTC by pgherveou

2024-03-04 10:54 UTC, pgherveou commented on substrate/frame/contracts/src/benchmarking/mod.rs
We could also introduce a `seal_terminate_per_locked_dependency` but the extra PoV should be pretty low and will be refunded anyway with [PoV Reclaim](https://github.com/paritytech/polkadot-sdk/pull/1462) the

2024-03-04 16:52 UTC, xermicus approved these changes

2024-03-04 16:55 UTC, xermicus commented
Given we had incorrect benchmarks, shouldn't this change weights too?

2024-03-05 06:33 UTC, athei requested changes

2024-03-05 06:33 UTC, athei commented on substrate/frame/contracts/src/benchmarking/mod.rs
> +			deploy_body: Some(body::repeated_dyn(code_hash_len as _, vec![
Has to be repeated for the number of code_hashes not the length of each individual code_hash. Please add some assertion in the setup phase that the contract actually has these number of dependencies.

```suggestion
			deploy_body: Some(body::repeated_dyn(T::MaxDelegateDependencies::get(), vec![
```

2024-03-05 06:33 UTC, athei commented on substrate/frame/contracts/src/benchmarking/mod.rs
Let's wait for the benchmarks to see how bad it is. I don't think the reclaim is working, yet. The linked PR is only the node side. However, `terminate` is rare enough so that I wouldn't optimize too much for it so we are probably good.

2024-03-05 21:39 UTC, pgherveou commented
bot bench substrate-pallet --pallet=pallet_contracts

2024-03-06 00:31 UTC, athei approved these changes

2024-03-06 08:00 UTC, pgherveou commented
Weights [are much higher](https://weights.tasty.limo/compare?repo=polkadot-sdk&threshold=10&path_pattern=substrate%2Fframe%2F**%2Fsrc%2Fweights.rs%2Cpolkadot%2Fruntime%2F*%2Fsrc%2Fweights%2F**%2F*.rs%2Cpolkadot%2Fbridges%2Fmodules%2F*%2Fsrc%2Fweights.rs%2Ccumulus%2F**%2Fweights%2F*.rs%2Ccumulus%2F**%2Fweights%2Fxcm%2F*.rs%2Ccumulus%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=time&old=master&new=pg/contracts-fix-delegate_dependency-length-in-benchmark) (194%) as expected

Since this is a rare operation and PoV refund is around the corner (runtime PR merged [here](https://github.com/paritytech/polkadot-sdk/pull/3002) do you think it's still worth adding a terminate_per_locked_delegate_dependency?

2024-03-06 15:44 UTC, pgherveou commented
🔒  for now some of the generated pov are much larger
https://weights.tasty.limo/compare?repo=polkadot-sdk&threshold=10&path_pattern=substrate%2Fframe%2F**%2Fsrc%2Fweights.rs%2Cpolkadot%2Fruntime%2F*%2Fsrc%2Fweights%2F**%2F*.rs%2Cpolkadot%2Fbridges%2Fmodules%2F*%2Fsrc%2Fweights.rs%2Ccumulus%2F**%2Fweights%2F*.rs%2Ccumulus%2F**%2Fweights%2Fxcm%2F*.rs%2Ccumulus%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=proof&old=master&new=pg%2Fcontracts-benchmark-v2

2024-03-06 15:47 UTC, athei commented
Weird. Those should not have been affected by your changes here?

2024-03-08 18:48 UTC, merged