Remove getters from `im-online` pallet
paritytech/polkadot-sdk pull request #3589
Opened 2024-03-06 08:38 UTC by s0me0ne-unkn0wn

Description TBD

2024-03-06 11:09 UTC, muraca requested changes
Thank you! 
This is a breaking change though, so please remove the R0 label and add the prdoc

2024-03-06 20:44 UTC, muraca approved these changes

2024-03-11 14:19 UTC, bkchr approved these changes

2024-03-11 14:27 UTC, alexggh approved these changes

2024-03-11 14:27 UTC, sandreim approved these changes

2024-03-11 15:12 UTC, merged