Make penpal-runtime's TrustedReserves more connfigurable (#3564) (patch for 1.8.0)
paritytech/polkadot-sdk pull request #3625
Opened 2024-03-08 12:57 UTC by bkontur

Backport of https://github.com/paritytech/polkadot-sdk/pull/3564

Expected patches for (1.8.0):
- penpal-runtime `0.16.1`

2024-03-08 13:01 UTC, franciscoaguirre approved these changes

2024-03-08 15:24 UTC, seadanda approved these changes

2024-03-08 15:26 UTC, acatangiu requested changes
why all the `Cargo.lock` changes?

2024-03-09 21:57 UTC, bkontur commented
> why all the `Cargo.lock` changes?

I think, because actual `Cargo.lock`  has not been pushed after the last patch-release from `release-crates-io-v1.8.0`.
@Morganamilo right? I think it would be better for next patch-release if you could push also actual `Cargo.lock`.

E.g. actual version of `asset-hub-rococo-integration-tests` in this branch is really [0.1.0](https://github.com/paritytech/polkadot-sdk/blob/release-crates-io-v1.8.0/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-rococo/Cargo.toml#L2-L3) so the `Cargo.lock` change is correct:
```
[[package]]
name = "asset-hub-rococo-integration-tests"
- version = "1.0.0"
+ version = "0.1.0"
```

You can try it with checkout of `release-crates-io-v1.8.0` and  run `cargo build` and it will automatically change `Cargo.lock`
```
> git checkout release-crates-io-v1.8.0
>
> git status
On branch release-crates-io-v1.8.0
Your branch is up to date with 'origin/release-crates-io-v1.8.0'.

nothing to commit, working tree clean

>
> cargo build
>
> git status 
On branch release-crates-io-v1.8.0
Your branch is up to date with 'origin/release-crates-io-v1.8.0'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Cargo.lock

```

2024-03-11 09:30 UTC, acatangiu approved these changes

2024-03-11 09:30 UTC, merged