Re-establish pallet_revive weights baseline
paritytech/polkadot-sdk pull request #5845
Opened 2024-09-26 12:53 UTC by mordamax

- baseline
- update pipeline name

2024-09-26 12:53 UTC, mordamax commented
/cmd bench --pallet=pallet_revive

2024-09-26 13:53 UTC, mordamax commented
/cmd bench --pallet=pallet_revive --runtime=dev

2024-09-27 09:57 UTC, athei commented
It doesn't compile because we renamed some benchmarks but never fixed the places where the benchmarks were used. The benchmarking worked fine I guess just need some follow up fixes here.

I can push the fixes to this PR later.

2024-09-27 10:19 UTC, athei commented
So I fixed the compilation. But because the `instr` benchmark is so whacky it foes down to zero and we and up with divide by zero panics. Have to look into this later.

2024-09-28 12:06 UTC, athei commented
/cmd bench --pallet=pallet_revive --runtime=dev

2024-09-28 12:07 UTC, athei commented
I changed the `instr` benchmark so that it should no longer return to little weight. It is still bogus but at leats benchmarking should not work.

2024-09-28 22:36 UTC, mordamax commented
/cmd --help --clean

2024-09-30 07:40 UTC, athei commented
Do you know why it didn't work?

2024-09-30 07:51 UTC, alvicsam requested changes

2024-09-30 07:51 UTC, alvicsam commented on .github/workflows/cmd-tests.yml
> +  test-cmd:
```suggestion
  test-cmd-bot:
```
I would use this name because `test-cmd` is still confusing imo

2024-09-30 09:42 UTC, mordamax commented
> Do you know why it didn't work?

```
2024-09-28T12:33:05.093879Z  WARN frame_omni_bencher: The FRAME omni-bencher is not yet battle tested - double check the results.    
2024-09-28T12:33:05.094321Z  INFO frame_benchmarking_cli::pallet::command: Loading WASM from target/release/wbuild/kitchensink-runtime/kitchensink_runtime.wasm    
2024-09-28T12:33:10.291775Z ERROR frame_benchmarking_cli::pallet::command: Please pick one of the available presets with `--genesis-builder-preset=<PRESET>`. Available presets (0): []. Error: "The preset with name Some(\"development\") is not available."    
Error: Input("The preset with name Some(\"development\") is not available.")
```

2024-09-30 11:24 UTC, mordamax commented
/cmd bench --pallet=pallet_revive --runtime=dev

2024-09-30 11:52 UTC, mordamax commented
/cmd bench --pallet=pallet_revive --runtime=dev --clean

2024-10-01 21:26 UTC, mordamax commented
bot bench substrate-pallet --pallet=pallet_revive

2024-10-01 22:19 UTC, mordamax commented
bot bench substrate-pallet --pallet=pallet_revive

2024-10-02 06:55 UTC, athei approved these changes

2024-10-02 07:57 UTC, alvicsam approved these changes

2024-10-02 09:17 UTC, pgherveou approved these changes

2024-10-02 10:39 UTC, athei commented
Why are those flaky tests required again? It is really starting to get annoying.

2024-10-03 21:28 UTC, merged