Membership pallet try state
paritytech/polkadot-sdk pull request #5850
Opened 2024-09-26 17:45 UTC by dharjeezy

This PR introduces try state hook into the Membership Pallet.
It also defines the invariants that holds for the pallet.

Part of: https://github.com/paritytech/polkadot-sdk/issues/239

2026-04-13 09:38 UTC, ggwpez approved these changes

2026-04-14 21:45 UTC, bkchr approved these changes

2026-04-14 21:45 UTC, bkchr commented on substrate/frame/membership/src/mock.rs
> +}
```suggestion
#[derive(Default)]
pub struct ExtBuilder;
```

2026-04-14 21:45 UTC, bkchr commented on substrate/frame/membership/src/lib.rs
> +			members.len() <= T::MaxMembers::get() as usize,
```suggestion
			Members::<T, I>::decode_len().unwrap_or(0) <= T::MaxMembers::get() as usize,
```

Otherwise too many would just be swallowed.

2026-04-14 21:45 UTC, bkchr commented on substrate/frame/membership/src/lib.rs
> +	pub fn do_try_state() -> Result<(), sp_runtime::TryRuntimeError> {
```suggestion
	pub(crate) fn do_try_state() -> Result<(), sp_runtime::TryRuntimeError> {
```

2026-05-29 08:56 UTC, muharem approved these changes

2026-05-29 08:58 UTC, muharem requested changes
tests with benchmarks feature are failing

2026-06-01 12:02 UTC, dharjeezy commented
this is good for merge now @muharem

2026-06-01 13:43 UTC, muharem approved these changes

2026-06-28 19:20 UTC, merged