XcmPaymentApi: take into account AH sufficient assets
paritytech/polkadot-sdk pull request #6033
Opened 2024-10-13 16:38 UTC by mrshiposha

# Description

This PR provides:
* The `sufficient_assets` function to the `pallet-assets`.
* Report all sufficient assets as acceptable as XCM execution fees in addition to the Relay's token
* Converting the native fees into the selected sufficient asset to be returned from the `query_weight_to_asset_fee`.

2024-10-13 16:38 UTC, mrshiposha commented
CC @franciscoaguirre

2024-10-14 07:59 UTC, acatangiu requested changes
Asset sufficiency does _not_ mean asset can be _directly_ used for paying fees.

For finding assets that can be (indirectly) used for paying fees, you need to check the list of pools. Specifying any asset in a pool paired with DOT/KSM/WND as the fee payment asset, will result in just-in-time auto swap for DOT just enough to pay for fees.

Maybe we actually need some other runtime API for exposing list of active pools if we don't have it already?
@franciscoaguirre has more info

2024-10-14 07:59 UTC, acatangiu commented on cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
> +				.map(AssetId);
Asset sufficiency doesn't mean it can be used to buy weight, i.e. directly pay for fees.

Asset sufficiency **only** means the asset is _sufficient_ for the account to exist, i.e. it doesn't require DOT ED on that account.

This code is incorrect as it will return assets as suitable for directly paying fees which is not the case. I suggest you always add a simple emulator test to PoC any XCM config change.

2024-10-14 08:15 UTC, mrshiposha commented on cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
> +				.map(AssetId);
>Asset sufficiency doesn't mean it can be used to buy weight, i.e. directly pay for fees.

Hmm, there are comments in the code stating the opposite...

https://github.com/paritytech/polkadot-sdk/blob/d1c115b6197bf6c45d5640594f0432e6c2781a4f/cumulus/parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs#L421-L446

Also, I ran Westend AssetHub locally. I haven't set up the pools, but sufficient assets (both from `Assets` and `ForeignAssets`) worked as XCM execution fees.  The code under the linker above provides this functionality.

2024-10-14 08:41 UTC, mrshiposha commented on cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
> +				.map(AssetId);
There are even tests for that:
* ForeignAssets: https://github.com/paritytech/polkadot-sdk/blob/d1c115b6197bf6c45d5640594f0432e6c2781a4f/cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs#L489-L568
* Assets: https://github.com/paritytech/polkadot-sdk/blob/d1c115b6197bf6c45d5640594f0432e6c2781a4f/cumulus/parachains/runtimes/assets/asset-hub-westend/tests/tests.rs#L411-L487

2024-10-14 08:55 UTC, acatangiu commented on cumulus/parachains/runtimes/assets/asset-hub-westend/src/lib.rs
> +				.map(AssetId);
ah yes, it is unfortunate that the `TakeFirstAssetTrader` is still there.. afaik the plan was to remove it once we have some pools set up and can rely on the one above it `SwapFirstAssetTrader`.

The reason to remote `TakeFirstAssetTrader` is that it doesn't (and can't) correctly account the economic value of weight. Depending on market movements buying weight with sufficient assets can be abused to potentially severely undercut fees.

AFAIK the plan still is to remove `TakeFirstAssetTrader` from system chains.

2024-10-15 14:42 UTC, acatangiu commented
I think this is superseeded by https://github.com/paritytech/polkadot-sdk/pull/5599?

cc @franciscoaguirre

2024-10-15 15:37 UTC, franciscoaguirre commented
Yes, sufficient assets should only mean valid for ED but not necessarily for fees

2024-10-15 15:39 UTC, acatangiu commented
@mrshiposha does https://github.com/paritytech/polkadot-sdk/pull/5599 cover your needs?

2024-10-15 15:39 UTC, mrshiposha commented
Closing in favor of #5599

2024-10-15 15:39 UTC, closed without merging