Dedup nomination targets
paritytech/polkadot-sdk pull request #6307
Opened 2024-10-31 07:47 UTC by AurevoirXavier

Deduplicate the targets during the nomination process.

This was found by the Subscan team. There is only one special account in Polkadot. The Polkadot Apps UI will filter for the users. I assume this uses a custom client to submit the extrinsic.

2024-10-31 10:11 UTC, kianenigma commented
@gpestana @Ank4n

2024-10-31 10:34 UTC, Ank4n reviewed
Just one comment; otherwise, lgtm!

We don’t need to migrate the single account. When they update their nomination, any duplicates will be removed automatically. (You could add a unit test to demonstrate that updating nominations removes old duplicates as well.)

Thank you for your PR!

2024-10-31 10:34 UTC, Ank4n commented on substrate/frame/staking/src/pallet/mod.rs
> +			targets.dedup();
I would move this after the `targets.len() <= T::NominationsQuota::get_quota(ledger.active)` check so we are not deduplicating against an unnecessary long vec.

2024-11-02 00:39 UTC, Ank4n approved these changes

2024-11-05 08:45 UTC, gui1117 commented on substrate/frame/staking/src/pallet/mod.rs
> +			targets.dedup();
This removes only consecutive duplicates, do we enforce it is sorted somewhere?

2024-11-05 10:18 UTC, kianenigma requested changes
https://github.com/paritytech/polkadot-sdk/pull/6307/files#r1828951375

2024-11-07 15:48 UTC, AurevoirXavier commented on substrate/frame/staking/src/pallet/mod.rs
> +				.map(|t| T::Lookup::lookup(t).map_err(DispatchError::from))
Could we use `AccountId` here? I'm not sure why we are using the `Lookup` type in this context.

2024-12-21 09:51 UTC, AurevoirXavier commented
@kianenigma @gui1117 🙏

2025-01-08 03:05 UTC, aurexav commented
Hi, are we going to merge this?

2025-01-08 03:57 UTC, gui1117 approved these changes
nominate weight is proportional to N, with this PR it is actually `O(n*log(n))` because we are sorting.
(rust is using timsort so worst case is `O(n log n)`.)

Maybe the benchmark should be changed to actually benchmark for the worst case, but I think it is fine as it is.

2025-01-21 21:11 UTC, Ank4n commented
> nominate weight is proportional to N, with this PR it is actually `O(n*log(n))` because we are sorting. (rust is using timsort so worst case is `O(n log n)`.)
> 
> Maybe the benchmark should be changed to actually benchmark for the worst case, but I think it is fine as it is.

Since n is a small number (16 for dot, 24 for kusama), I think this is okay.

2025-01-21 21:17 UTC, Ank4n commented
@kianenigma Could you review the changes to see if they’re acceptable to you and merge them? They LGTM.

2025-02-10 02:14 UTC, aurexav commented
Up...

2026-07-11 18:57 UTC, closed without merging