Migrate `pallet-authorship` to umbrella crate
paritytech/polkadot-sdk pull request #6620
Opened 2024-11-22 23:18 UTC by runcomet

Part of https://github.com/paritytech/polkadot-sdk/issues/6504

2024-11-29 14:15 UTC, runcomet commented
@re-gius recent push corrects the `try-runtime` feature flag in the Cargo.toml file

2024-12-17 14:50 UTC, re-gius requested changes
Please refer to the guidelines from [here](https://github.com/paritytech/polkadot-sdk/issues/6504)

I should mainly work with preludes and add items to then when possible.

2025-01-07 14:22 UTC, re-gius reviewed
Just undo changes to the `Cargo.lock` file and then ping me for an approval

2025-01-07 14:22 UTC, re-gius commented on Cargo.lock
>   "futures-lite 2.3.0",
Please undo changes to this file since it is not relevant to the PR

2025-01-09 20:01 UTC, runcomet commented on Cargo.lock
>   "futures-lite 2.3.0",
copied the `Cargo.lock` file from the main branch

2025-01-09 20:02 UTC, runcomet commented
please review @re-gius

2025-01-17 11:42 UTC, re-gius commented on substrate/frame/authorship/Cargo.toml
> +frame = { workspace = true, features = ["experimental", "runtime"] }
```suggestion
frame = { workspace = true, features = ["runtime"] }
```

2025-01-20 16:15 UTC, re-gius approved these changes

2025-01-26 01:42 UTC, runcomet commented
please review @kianenigma

2025-05-06 16:42 UTC, closed without merging