Introduction of Approval Slashes [Disabling Strategy Stage 4]
paritytech/polkadot-sdk pull request #6827
Opened 2024-12-10 12:54 UTC by Overkillus

Implementation of Stage 4 of the new [Disabling Strategy](https://github.com/paritytech/polkadot-sdk/issues/4359). 

Stage 3 needs to be deployed before this goes live. ([Stage 3 PR](https://github.com/paritytech/polkadot-sdk/pull/5724))

Currently only backers are ever slashed as a result of disputes.

This PR creates 3 types of offences with respective slashes:
- BackingInvalid (100%) -> hard punishment as backers bear all the responsbility for validity
- ForInvalid (2%) -> minor punishment to deter lazy validators
- AgainstValid (0%) -> very minor punishment (this causes disablement so opp cost)

Closes #4746

2025-05-15 07:12 UTC, ordian requested changes
As we discussed, the way it's currently implemented makes it hard to deploy with too many breaking changes. I've dropped my proposal below how to make this change less breaking and not require a backport for the node side.

2025-05-15 07:12 UTC, ordian commented on prdoc/pr_6827.prdoc
> +    If you validator raises or supports fake alarms (disputes against
```suggestion
    If your validator raises or supports fake alarms (disputes against
```

2025-05-15 07:12 UTC, ordian commented on prdoc/pr_6827.prdoc
> +- name: polkadot-primitives
with my suggestions, will be minor for `polkadot-runtime-parachains` and a few other crates (once runtime api are implemented)

2025-05-15 07:12 UTC, ordian commented on polkadot/runtime/parachains/src/disputes/slashing.rs
> +//! Our implementation looks like a hybrid of `im-online` and `grandpa
im-online is gone now, so might be a good time to remove this reference.

2025-05-26 08:24 UTC, ordian reviewed
on the first pass the logic looks correct, but we'll need to:
1. test this extensively
2. make sure it's safe to enable as is (probably need to figure out spurious disputes first)

2025-05-26 08:24 UTC, ordian commented on polkadot/runtime/parachains/src/disputes/slashing.rs
> +					Err(_) => None, // Skip if conversion fails (e.g., variant not representable in old format)
this should be logged probably, although during the migration period while we spam spamming approval checkers, but the runtime api is not upgraded yet, this could be spammy - maybe an info level?

2025-05-26 08:24 UTC, ordian commented on polkadot/zombienet_tests/functional/0020-validator-disabling-spam.zndsl
> +Description: Test validator disabling effects
please use zombienet-sdk for any new zombienet tests, we should be able to make it less flaky and test more scenarios with confidence

2025-05-26 15:00 UTC, sandreim reviewed
LGTM. Unfortunately it seems we cannot introduce the new runtime API now through a backport, but it's fine if it comes in another PR and release.

2025-05-26 15:00 UTC, sandreim commented on prdoc/pr_6827.prdoc
> +    of the era, which will potentially reduce era point gains.
I think it will for sure reduce era points.

2025-05-26 15:00 UTC, sandreim commented on polkadot/runtime/parachains/src/disputes/slashing.rs
> +		let backers: BTreeSet<_> = backers.into_iter().collect();
Is there a particular reason why we want to use `BTreeSet`  and not `HashSet`? We don't seem to need the ordering and also attacker would not be able to control the hash collisions to slow the runtime down.

2025-05-27 01:08 UTC, ordian commented on polkadot/runtime/parachains/src/disputes/slashing.rs
> +		let backers: BTreeSet<_> = backers.into_iter().collect();
is this about effiency in the context of https://github.com/paritytech/polkadot-sdk/pull/8606? i doubt this is relevant here as the size of backers is limited by 5 (and for losers by 300) - we could even use sorted vecs, but using btreesets is type safer

2025-05-27 09:48 UTC, sw10pa commented on polkadot/runtime/parachains/src/disputes/migration.rs
> +			}
Okay, thanks for explaining!

2025-05-28 10:23 UTC, Overkillus commented on polkadot/runtime/parachains/src/disputes/migration.rs
> +		fn on_runtime_upgrade() -> Weight {
Hmm... you might be right. Initially they were not but I changed the encoding and they should be compatible now.

2025-05-30 13:09 UTC, Overkillus commented on polkadot/runtime/parachains/src/disputes/migration.rs
> +		fn on_runtime_upgrade() -> Weight {
verified consistency, thanks @tdimitrov 🚀 

removed migration

2025-06-03 19:56 UTC, eskimor approved these changes

2025-06-04 18:13 UTC, ordian commented on polkadot/zombienet_tests/functional/0020-validator-disabling-spam.zndsl
> +Description: Test validator disabling effects
I suggest to remove this test for now and implement a proper zombienet-sdk one in a separate PR

2025-06-04 18:18 UTC, ordian commented on prdoc/pr_6827.prdoc
> +  bump: minor
```suggestion
  bump: minor
- name: polkadot-runtime-parachains
  bump: major
```

Technically, this is semver breaking change..

2025-06-05 12:46 UTC, ordian commented
I've looked into SemVer breaking changes of disabling PR and not sure if it's possible to avoid them completely. The problem is that [report_offence](https://github.com/paritytech/polkadot-sdk/blob/d054ac7dbac54abb692a06e78bd3e5d1a4da5ec9/polkadot/runtime/parachains/src/disputes/slashing.rs#L314-L316) method is used in both on-chain and off-chain slashing. If we want to use new offence type in on-chain slashing, we have to make a breaking change to `SlashingOffence` type.

2025-06-05 15:23 UTC, merged

2025-07-11 11:31 UTC, Polkadot-Forum commented
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-digest-11-jul-2025/13707/1