pallet-revive: Fix docs.rs
paritytech/polkadot-sdk pull request #6896
Opened 2024-12-14 10:50 UTC by athei

- Fixed failing docs.rs build for `pallet-revive-uapi` by fixing a wring attribute in the manifest (we were using `default-target` instead of `targets`)
-  Removed the macros defining host functions because the cfg attributes introduced in #6866 won't work on them
- Added an docs.rs specific attribute so that the `unstable-hostfn` feature tag will show up on the functions that are guarded behind it.

2024-12-16 15:41 UTC, athei commented
bot fmt

2024-12-17 13:29 UTC, jarkkojs requested changes
I don't see prdoc entry, should this have one? Description could explain migration to unstable_hostfn, which would then also help to review the PR overall.

I mean structure of this is like:

1. There's actually only one quite scoped change.
2. Rest "ripples" from that.

So explaining 1 would help others to understand this.

2024-12-17 16:20 UTC, athei commented
/cmd prdoc --audience runtime_dev

2024-12-17 16:21 UTC, athei commented
Ooops. Yeah we need a prdoc in order to bump the pallets on release.

2024-12-17 16:22 UTC, athei commented on substrate/frame/contracts/uapi/Cargo.toml
> +targets = ["wasm32-unknown-unknown"]
Have you read the PR description? It's the first point there.

2024-12-18 18:04 UTC, jarkkojs commented
> Ooops. Yeah we need a prdoc in order to bump the pallets on release. Generated from PR description.

Hmm... there's a way to generate it? :-) I've created the file manually.

2024-12-18 18:05 UTC, jarkkojs commented on prdoc/pr_6896.prdoc
> +    - Fixed failing docs.rs build for `pallet-revive-uapi` by fixing a wring attribute in the manifest (we were using `default-target` instead of `targets`)
wring i.e. wiring?

2024-12-18 18:06 UTC, jarkkojs commented on prdoc/pr_6896.prdoc
> +    - Fixed failing docs.rs build for `pallet-revive-uapi` by fixing a wring attribute in the manifest (we were using `default-target` instead of `targets`)
this is my only complaint, otherwise makes sense

2024-12-18 19:53 UTC, jarkkojs approved these changes

2024-12-18 22:13 UTC, merged